stages:
  - kubernetes

kubernetes:
  stage: kubernetes
  image: alpine/k8s:1.22.6
  environment:
    name: k8s
    url: https://std-014-65.k8s.praktikum-services.tech
  before_script:
    - mkdir -p ~/.kube
    - chmod 700 ~/.kube
    - cat "$kubeconfig" > ~/.kube/config
    - chmod 644 ~/.kube/config
  script:
    - kubectl apply -f kubernetes/backend/
    - kubectl apply -f kubernetes/backend-report/
    - kubectl apply -f kubernetes/frontend/
  only:
    changes:
      - kubernetes/**/*
