---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}nginx-conf"
data:
  default.conf: |
    server {

    listen {{ .Values.containerPort }};

    location / {
    root   /usr/share/nginx/html;
    index  index.html;
    try_files $uri $uri/ /index.html;
    }

    location /api {
      proxy_pass http://{{ .Values.global.backendName }}:{{ .Values.global.backendPort }};
    }
    }
