---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: {{ .Chart.Name }}
   labels:
     app: {{ .Chart.Name }}
spec:
  # В кластере может быть несколько Ingress Controllers, мы используем NGINX
  ingressClassName: "nginx"
  tls:
    - hosts:
        - {{ .Values.ingressHost }}
  rules:
    # Хост определяет правило направления траффика по доменному имени
  - host: {{ .Values.ingressHost }}
    http:
      # Для различных путей в URL можно указать различные бэкенд-сервисы
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Заранее создан сервис типа ClusterIP
            # Он выступает в качестве бэкенда нашего Ingress 
            name: {{ .Chart.Name }}
            port:
              # У сервиса может быть несколько портов, указываем нужный нам 
              number: {{ .Values.ingressPort }}
