---
apiVersion: v1
kind: Service
metadata:
   name: {{ .Chart.Name }}
   labels:
     app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Chart.Name }}
