---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  labels:
    app: backend
data:     
 db: bW9uZ29kYjovL3N0ZC0wMTQtNjU6RGV2b3BzMTIzIUByYzFhLW5yM200eW10cnI1cWpqZTkubWRiLnlhbmRleGNsb3VkLm5ldDoyNzAxOC9zdGQtMDE0LTY1P3Rscz10cnVlJnJlcGxpY2FTZXQ9cnMwMQ== 
 host: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi10d2lhNjducHJkanBudGhkLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDE0LTY1
 username: c3RkLTAxNC02NQ==
 password: TmV3MTIzNDUh
type: Opaque
---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJzdGQtMDE0LTY1IiwicGFzc3dvcmQiOiI3OVM2M2J3ayIsImF1dGgiOiJjM1JrTFRBeE5DMDJOVG8zT1ZNMk0ySjNhdz09In19fQ==

type: kubernetes.io/dockerconfigjson 
