---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  labels:
    app: backend
data:     
 db: 
 host: 
 username: 
 password: 
type: Opaque
---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4TkMweE1qbzROSFk0TVZkVlp3PT0iCgkJfQoJfQp9

type: kubernetes.io/dockerconfigjson 
