---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
   name: {{ .Chart.Name }}
   labels:
     app: {{ .Chart.Name }}
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{  .Values.averageUtilization }}
