---
kind: Secret
apiVersion: v1
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJzdGQtMDE0LTY1IiwicGFzc3dvcmQiOiI3OVM2M2J3ayIsImF1dGgiOiJjM1JrTFRBeE5DMDJOVG8zT1ZNMk0ySjNhdz09In19fQ==

type: kubernetes.io/dockerconfigjson
