---
apiVersion: v1
kind: Secret
metadata:
   name: {{ .Chart.Name }}
   labels:
     app: {{ .Chart.Name }}

data:
 db: {{  .Values.global.mongodb }}
 host: {{ .Values.data.host }}
 username: {{ .Values.data.username }}
 password: {{ .Values.data.password }}
type: Opaque


