---
apiVersion: v1
kind: Secret
metadata:
  name: backend-report
  labels:
    app: backend-report
data:
  db: 
type: Opaque
---

kind: Secret
apiVersion: v1
metadata:
  name: regcred
data:
  .dockerconfigjson: 

type: kubernetes.io/dockerconfigjson
