---
apiVersion: v1
kind: Secret
metadata:
  name: backend-report
  labels:
    app: backend-report
data:
  db: 
type: Opaque
---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIloybDBiR0ZpTFdOcExYUnZhMlZ1T2xaellrZDFhRkZ4ZW5oUmNuVXlZMjVMVlRaVCIKCQl9Cgl9Cn0K

type: kubernetes.io/dockerconfigjson 
