---
apiVersion: v1
kind: Secret
metadata:
  name: backend-report
  labels:
    app: backend-report
data:
  db: bW9uZ29kYjovL3N0ZC0wMTQtNjU6RGV2b3BzMTIzIUByYzFhLW5yM200eW10cnI1cWpqZTkubWRiLnlhbmRleGNsb3VkLm5ldDoyNzAxOC9zdGQtMDE0LTY1P3Rscz10cnVlJnJlcGxpY2FTZXQ9cnMwMQ==
type: Opaque
---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJzdGQtMDE0LTY1IiwicGFzc3dvcmQiOiI3OVM2M2J3ayIsImF1dGgiOiJjM1JrTFRBeE5DMDJOVG8zT1ZNMk0ySjNhdz09In19fQ==

type: kubernetes.io/dockerconfigjson 
